sudo: false
language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run prepush

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always
